// Quick runtime smoke test for the domain schemas.
// Not part of the build; run with `node scripts/check-domain.mjs`.

import {
  User,
  Agent,
  Space,
  Event,
  Work,
  List,
  ListItem,
  Agenda,
  AgendaItem,
  AgendaInvite,
  Interaction,
  Follow,
  Verification,
  Boost,
  FeedItem,
  SearchFilters,
} from '../src/domain/index.ts';

const now = new Date().toISOString();

const samples = {
  User: {
    id: 'u1',
    email: 'a@b.co',
    phone: null,
    displayName: 'Lívia',
    handle: '@liviak',
    avatarUrl: null,
    coverUrl: null,
    bio: '',
    locationLabel: null,
    primaryCity: null,
    primaryState: null,
    primaryCountry: 'BR',
    trustTier: 'email',
    role: 'member',
    agentId: null,
    preferences: { language: 'pt-BR', pushEnabled: true, emailEnabled: true },
    createdAt: now,
    updatedAt: now,
    lastSeenAt: null,
  },
  Agent: {
    id: 'a1',
    ownerUserId: 'u1',
    kind: 'artist',
    displayName: 'Lívia K.',
    slug: 'livia-k',
    tagline: '',
    bio: '',
    manifesto: '',
    disciplines: ['Visual Arts'],
    techniques: [],
    professions: [],
    languages: [],
    city: 'São Paulo',
    state: 'SP',
    country: 'BR',
    neighborhood: null,
    identity: {},
    socialLinks: {},
    avatarUrl: null,
    coverUrl: null,
    portfolioImages: [],
    isPublic: true,
    isVerified: false,
    acceptsCommissions: false,
    acceptsBookings: false,
    createdAt: now,
    updatedAt: now,
  },
  Space: {
    id: 's1',
    slug: 'white-cube',
    ownerAgentId: null,
    managerUserIds: [],
    name: 'The White Cube',
    kind: 'gallery',
    description: '',
    address: {
      street: null,
      number: null,
      neighborhood: null,
      city: 'São Paulo',
      state: 'SP',
      country: 'BR',
      postalCode: null,
    },
    geo: null,
    capacity: null,
    amenities: [],
    priceRange: null,
    openingHours: {},
    contact: {},
    coverUrl: null,
    images: [],
    tags: [],
    isVerified: false,
    isPublished: true,
    createdAt: now,
    updatedAt: now,
  },
  Event: {
    id: 'e1',
    slug: 'sombras-digitais',
    title: 'Sombras Digitais',
    kind: 'exhibition',
    subtitle: '',
    description: '',
    coverUrl: null,
    images: [],
    startsAt: now,
    endsAt: null,
    timezone: 'America/Sao_Paulo',
    spaceId: null,
    locationLabel: null,
    geo: null,
    organizerAgentIds: [],
    featuredAgentIds: [],
    categories: [],
    tags: [],
    ticketing: {
      isFree: true,
      priceFromBRL: null,
      priceToBRL: null,
      externalUrl: null,
      soldInternally: false,
      capacity: null,
      ticketsSold: 0,
    },
    ageRating: null,
    isPublished: true,
    isCancelled: false,
    stats: { saves: 0, likes: 0, attended: 0 },
    createdAt: now,
    updatedAt: now,
  },
  Work: {
    id: 'w1',
    authorAgentId: 'a1',
    title: 'Sombras I',
    description: '',
    medium: 'digital',
    technique: null,
    year: 2024,
    dimensions: null,
    durationSeconds: null,
    coverUrl: null,
    images: [],
    audioUrl: null,
    videoUrl: null,
    editionOf: null,
    priceBRL: null,
    isForSale: false,
    isSold: false,
    tags: [],
    isPublished: true,
    stats: { saves: 0, likes: 0, views: 0 },
    createdAt: now,
    updatedAt: now,
  },
  List: {
    id: 'l1',
    ownerUserId: 'u1',
    name: 'Contrataria',
    preset: 'contrataria',
    description: '',
    isPublic: false,
    coverUrl: null,
    itemCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  ListItem: {
    id: 'li1',
    listId: 'l1',
    targetType: 'agent',
    targetId: 'a1',
    note: '',
    orderIndex: 0,
    addedAt: now,
  },
  Agenda: {
    id: 'ag1',
    ownerUserId: 'u1',
    name: 'Minha semana',
    description: '',
    visibility: 'private',
    members: [],
    coverUrl: null,
    itemCount: 0,
    createdAt: now,
    updatedAt: now,
  },
  AgendaItem: {
    id: 'ai1',
    agendaId: 'ag1',
    addedByUserId: 'u1',
    eventId: 'e1',
    customTitle: null,
    customLocation: null,
    startsAt: now,
    endsAt: null,
    status: 'interested',
    notes: '',
    reminderMinutesBefore: null,
    createdAt: now,
    updatedAt: now,
  },
  AgendaInvite: {
    id: 'ainv1',
    agendaId: 'ag1',
    invitedUserId: 'u2',
    invitedByUserId: 'u1',
    role: 'editor',
    status: 'pending',
    createdAt: now,
    respondedAt: null,
  },
  Interaction: {
    id: 'i1',
    actorUserId: 'u1',
    kind: 'save',
    targetType: 'event',
    targetId: 'e1',
    surface: 'discover_mixed',
    dwellMs: null,
    metadata: {},
    createdAt: now,
  },
  Follow: {
    id: 'f1',
    followerUserId: 'u1',
    targetType: 'agent',
    targetId: 'a1',
    createdAt: now,
  },
  Verification: {
    id: 'v1',
    userId: 'u1',
    kind: 'cpf',
    status: 'pending',
    maskedValue: null,
    documentRef: null,
    documentAiJobId: null,
    rejectionReason: null,
    submittedAt: null,
    verifiedAt: null,
    expiresAt: null,
  },
  Boost: {
    id: 'b1',
    actorUserId: 'u1',
    targetType: 'event',
    targetId: 'e1',
    budgetBRL: 100,
    spentBRL: 0,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    targetAudience: {
      cities: [],
      disciplines: [],
      ageRanges: [],
      radiusKm: null,
    },
    status: 'draft',
    startsAt: now,
    endsAt: now,
    createdAt: now,
    updatedAt: now,
  },
  SearchFilters: {
    kinds: ['event'],
    city: 'São Paulo',
    neighborhood: null,
    radiusKm: null,
    dateFrom: null,
    dateTo: null,
    categories: [],
    disciplines: [],
    techniques: [],
    agentKinds: [],
    ageRanges: [],
    genders: [],
    races: [],
    spaceKinds: [],
    eventKinds: [],
    priceMax: null,
    query: '',
  },
};

const schemas = {
  User,
  Agent,
  Space,
  Event,
  Work,
  List,
  ListItem,
  Agenda,
  AgendaItem,
  AgendaInvite,
  Interaction,
  Follow,
  Verification,
  Boost,
  SearchFilters,
};

let failed = 0;
for (const [name, schema] of Object.entries(schemas)) {
  const r = schema.safeParse(samples[name]);
  if (!r.success) {
    failed++;
    console.error(`FAIL ${name}`);
    console.error(JSON.stringify(r.error.issues, null, 2));
  } else {
    console.log(`OK   ${name}`);
  }
}

// FeedItem is a discriminated union; exercise one arm.
const feed = FeedItem.safeParse({
  id: 'fi1',
  reason: 'algorithmic',
  score: 0.9,
  boostId: null,
  kind: 'event',
  data: samples.Event,
});
if (!feed.success) {
  failed++;
  console.error('FAIL FeedItem');
  console.error(JSON.stringify(feed.error.issues, null, 2));
} else {
  console.log('OK   FeedItem');
}

if (failed) {
  console.error(`\n${failed} schema(s) failed`);
  process.exit(1);
} else {
  console.log('\nAll schemas parsed clean.');
}
